name: Docker Build & Push

on:
  push:
    branches:
      - main   # ya tumhara default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #  Log in to Docker Hub (optional)
      # Tum chaaho to DockerHub credentials GitHub Secrets me dal do
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #  Build Docker Image
      - name: Build Docker image
        run: docker build -t ai-dataset-agent .

      # Push Docker Image (optional)
      - name: Push Docker image
        run: docker push ai-dataset-agent
        # Agar GitHub Container Registry use karna ho, replace docker push
